# Working on KM 11

Let's import the data

In [1]:
import pandas as pd
import numpy as np


movie = pd.read_csv("movie_sent_clust.csv")
movie

Unnamed: 0  movie_id  intelligent      real  touching  relatable  \
0              0      8984     0.189474  0.147368  0.242105   0.168421   
1             95      8985     0.137500  0.187500  0.275000   0.162500   
2            175      8986     0.103093  0.051546  0.247423   0.092784   
3            272      8987     0.063158  0.094737  0.294737   0.073684   
4            367      8988     0.193548  0.225806  0.215054   0.172043   
...          ...       ...          ...       ...       ...        ...   
2613      234446     13526     0.042105  0.031579  0.042105   0.147368   
2614      234541     13527     0.329670  0.043956  0.098901   0.043956   
2615      234632     13528     0.018868  0.037736  0.037736   0.018868   
2616      234685     13529     0.125786  0.037736  0.113208   0.056604   
2617      234844     13532     0.222222  0.049383  0.037037   0.049383   

           sad  romantic  informative      mean  ...  GMM7_PCA  GMM8_PCA  \
0     0.073684  0.431579     0.200000  0.094737  ...         3         6   
1     0.025000  0.450000     0.100000  0.037500  ...         3         6   
2     0.010309  0.556701     0.051546  0.000000  ...         3         6   
3     0.031579  0.589474     0.042105  0.000000  ...         3         6   
4     0.053763  0.247312     0.182796  0.064516  ...         4         3   
...        ...       ...          ...       ...  ...       ...       ...   
2613  0.031579  0.084211     0.031579  0.010526  ...         6         5   
2614  0.120879  0.010989     0.010989  0.021978  ...         5         4   
2615  0.018868  0.000000     0.018868  0.037736  ...         1         0   
2616  0.106918  0.006289     0.025157  0.000000  ...         5         7   
2617  0.049383  0.012346     0.061728  0.000000  ...         1         7   

      GMM9_PCA  GMM10_PCA  ward_8  ward_9  ward_10  ward_11  ward_12  \
0            7          3       8       9       10       11       12   
1            7          3       8       9       10       11       12   
2            7          3       8       9       10       11       12   
3            7          3       8       9       10       11       12   
4            0          5       6       7        8        8        9   
...        ...        ...     ...     ...      ...      ...      ...   
2613         1          6       4       5        6        6        7   
2614         3          4       3       4        4        4        4   
2615         5          0       2       3        3        3        3   
2616         3          4       1       1        1        1        1   
2617         2          8       1       2        2        2        2   

                                     movie_name  
0                             A Brush with Love  
1                       A Christmas Arrangement  
2                     A Christmas for the Books  
3                      A Christmas in Tennessee  
4                             A Feeling of Home  
...                                         ...  
2613               Fast Times at Ridgemont High  
2614            The Girl with the Dragon Tattoo  
2615                      House on Haunted Hill  
2616  The Hobbit: The Battle of the Five Armies  
2617                         Star Trek: Nemesis  

[2618 rows x 62 columns]

Removing index

In [2]:
movie = movie.iloc[:,1:]

Let's put in movie_sent the sentiments

In [3]:
movie_sent = movie.iloc[:, 0:45] 
movie_sent

movie_id  intelligent      real  touching  relatable       sad  \
0         8984     0.189474  0.147368  0.242105   0.168421  0.073684   
1         8985     0.137500  0.187500  0.275000   0.162500  0.025000   
2         8986     0.103093  0.051546  0.247423   0.092784  0.010309   
3         8987     0.063158  0.094737  0.294737   0.073684  0.031579   
4         8988     0.193548  0.225806  0.215054   0.172043  0.053763   
...        ...          ...       ...       ...        ...       ...   
2613     13526     0.042105  0.031579  0.042105   0.147368  0.031579   
2614     13527     0.329670  0.043956  0.098901   0.043956  0.120879   
2615     13528     0.018868  0.037736  0.037736   0.018868  0.018868   
2616     13529     0.125786  0.037736  0.113208   0.056604  0.106918   
2617     13532     0.222222  0.049383  0.037037   0.049383  0.049383   

      romantic  informative      mean      fake  ...  info_real_int_insp  \
0     0.431579     0.200000  0.094737  0.021053  ...            0.176316   
1     0.450000     0.100000  0.037500  0.050000  ...            0.165625   
2     0.556701     0.051546  0.000000  0.030928  ...            0.087629   
3     0.589474     0.042105  0.000000  0.052632  ...            0.089474   
4     0.247312     0.182796  0.064516  0.064516  ...            0.206989   
...        ...          ...       ...       ...  ...                 ...   
2613  0.084211     0.031579  0.010526  0.042105  ...            0.042105   
2614  0.010989     0.010989  0.021978  0.010989  ...            0.104396   
2615  0.000000     0.018868  0.037736  0.075472  ...            0.028302   
2616  0.006289     0.025157  0.000000  0.012579  ...            0.094340   
2617  0.012346     0.061728  0.000000  0.037037  ...            0.108025   

      fun_outrag_mindless  fastpaced_thrilling_exciting  \
0                0.143860                      0.161404   
1                0.133333                      0.083333   
2                0.147766                      0.089347   
3                0.108772                      0.045614   
4                0.182796                      0.200717   
...                   ...                           ...   
2613             0.421053                      0.150877   
2614             0.040293                      0.542125   
2615             0.094340                      0.264151   
2616             0.115304                      0.446541   
2617             0.111111                      0.452675   

      scary_dist_edgy_thrill  origi_imagin_fresh_imag  \
0                   0.084211                 0.142105   
1                   0.043750                 0.156250   
2                   0.020619                 0.095361   
3                   0.015789                 0.092105   
4                   0.112903                 0.174731   
...                      ...                      ...   
2613                0.068421                 0.150000   
2614                0.373626                 0.288462   
2615                0.424528                 0.066038   
2616                0.172956                 0.243711   
2617                0.225309                 0.222222   

      sad_dramatic_deep_touching  fake_unrel_unorig_predic  sexy_glam_rom  \
0                       0.147368                  0.071053       0.217544   
1                       0.131250                  0.081250       0.220833   
2                       0.095361                  0.074742       0.230241   
3                       0.113158                  0.097368       0.228070   
4                       0.142473                  0.083333       0.161290   
...                          ...                       ...            ...   
2613                    0.047368                  0.026316       0.084211   
2614                    0.222527                  0.010989       0.084249   
2615                    0.061321                  0.066038       0.025157   
2616                    0.205975                  0.017296      

and a sepratae table with all the clusters

In [4]:
clusters = movie.iloc[:, 45:] 
clusters

KM6  KM7  KM8  KM9  KM10  KM11  GMM7_PCA  GMM8_PCA  GMM9_PCA  GMM10_PCA  \
0       3    1    6    1     5     2         3         6         7          3   
1       4    1    0    4     6     4         3         6         7          3   
2       4    1    0    4     6     4         3         6         7          3   
3       4    1    0    4     6     4         3         6         7          3   
4       3    5    6    1     5     2         4         3         0          5   
...   ...  ...  ...  ...   ...   ...       ...       ...       ...        ...   
2613    1    3    2    6     8     9         6         5         1          6   
2614    2    6    5    3     7     7         5         4         3          4   
2615    5    2    3    5     0     6         1         0         5          0   
2616    2    6    1    3     4     5         5         7         3          4   
2617    2    6    1    8     4     8         1         7         2          8   

      ward_8  ward_9  ward_10  ward_11  ward_12  \
0          8       9       10       11       12   
1          8       9       10       11       12   
2          8       9       10       11       12   
3          8       9       10       11       12   
4          6       7        8        8        9   
...      ...     ...      ...      ...      ...   
2613       4       5        6        6        7   
2614       3       4        4        4        4   
2615       2       3        3        3        3   
2616       1       1        1        1        1   
2617       1       2        2        2        2   

                                     movie_name  
0                             A Brush with Love  
1                       A Christmas Arrangement  
2                     A Christmas for the Books  
3                      A Christmas in Tennessee  
4                             A Feeling of Home  
...                                         ...  
2613               Fast Times at Ridgemont High  
2614            The Girl with the Dragon Tattoo  
2615                      House on Haunted Hill  
2616  The Hobbit: The Battle of the Five Armies  
2617                         Star Trek: Nemesis  

[2618 rows x 16 columns]

let's merge sentiments and KM11

In [5]:
movie_sent['KM11'] = clusters.KM11   #substitute km6 with another cluster vairable to insert it
movie_sent

movie_id  intelligent      real  touching  relatable       sad  \
0         8984     0.189474  0.147368  0.242105   0.168421  0.073684   
1         8985     0.137500  0.187500  0.275000   0.162500  0.025000   
2         8986     0.103093  0.051546  0.247423   0.092784  0.010309   
3         8987     0.063158  0.094737  0.294737   0.073684  0.031579   
4         8988     0.193548  0.225806  0.215054   0.172043  0.053763   
...        ...          ...       ...       ...        ...       ...   
2613     13526     0.042105  0.031579  0.042105   0.147368  0.031579   
2614     13527     0.329670  0.043956  0.098901   0.043956  0.120879   
2615     13528     0.018868  0.037736  0.037736   0.018868  0.018868   
2616     13529     0.125786  0.037736  0.113208   0.056604  0.106918   
2617     13532     0.222222  0.049383  0.037037   0.049383  0.049383   

      romantic  informative      mean      fake  ...  fun_outrag_mindless  \
0     0.431579     0.200000  0.094737  0.021053  ...             0.143860   
1     0.450000     0.100000  0.037500  0.050000  ...             0.133333   
2     0.556701     0.051546  0.000000  0.030928  ...             0.147766   
3     0.589474     0.042105  0.000000  0.052632  ...             0.108772   
4     0.247312     0.182796  0.064516  0.064516  ...             0.182796   
...        ...          ...       ...       ...  ...                  ...   
2613  0.084211     0.031579  0.010526  0.042105  ...             0.421053   
2614  0.010989     0.010989  0.021978  0.010989  ...             0.040293   
2615  0.000000     0.018868  0.037736  0.075472  ...             0.094340   
2616  0.006289     0.025157  0.000000  0.012579  ...             0.115304   
2617  0.012346     0.061728  0.000000  0.037037  ...             0.111111   

      fastpaced_thrilling_exciting  scary_dist_edgy_thrill  \
0                         0.161404                0.084211   
1                         0.083333                0.043750   
2                         0.089347                0.020619   
3                         0.045614                0.015789   
4                         0.200717                0.112903   
...                            ...                     ...   
2613                      0.150877                0.068421   
2614                      0.542125                0.373626   
2615                      0.264151                0.424528   
2616                      0.446541                0.172956   
2617                      0.452675                0.225309   

      origi_imagin_fresh_imag  sad_dramatic_deep_touching  \
0                    0.142105                    0.147368   
1                    0.156250                    0.131250   
2                    0.095361                    0.095361   
3                    0.092105                    0.113158   
4                    0.174731                    0.142473   
...                       ...                         ...   
2613                 0.150000                    0.047368   
2614                 0.288462                    0.222527   
2615                 0.066038                    0.061321   
2616                 0.243711                    0.205975   
2617                 0.222222                    0.111111   

      fake_unrel_unorig_predic  sexy_glam_rom  touching_wholesome_uplifting  \
0                     0.071053       0.217544                      0.182456   
1                     0.081250       0.220833                      0.220833   
2                     0.074742       0.230241                      0.274914   
3                     0.097368       0.228070                      0.263158   
4                     0.083333       0.161290                      0.143369   
...                        ...            ...                           ...   
2613                  0.026316       0.084211                      0.049123   
2614                  0.010989       0.084249                      0.040293   
2615                  0.066

### We are merging the group 1 and 4 because both romantic. Label "4" becomes "1"

In [6]:
movie_sent['KM11'] = movie_sent['KM11'].replace([4],1)
movie_sent.KM11.value_counts()

9     388
8     355
1     337
3     281
7     274
2     268
6     231
10    185
5     158
0     141
Name: KM11, dtype: int64

Let's replace the rest of the clusters in order to have a sequence from 0 to 8

In [7]:
movie_sent['KM11'] = movie_sent['KM11'].replace([5],4)
movie_sent['KM11'] = movie_sent['KM11'].replace([6],5)
movie_sent['KM11'] = movie_sent['KM11'].replace([7],6)
movie_sent['KM11'] = movie_sent['KM11'].replace([8],7)
movie_sent['KM11'] = movie_sent['KM11'].replace([9],8)
movie_sent['KM11'] = movie_sent['KM11'].replace([10],9)
movie_sent.KM11.value_counts()

8    388
7    355
1    337
3    281
6    274
2    268
5    231
9    185
4    158
0    141
Name: KM11, dtype: int64

Now we are going to standardize variables

In [8]:
movie_sent['KM11'] = movie_sent.KM11.astype('object')

In [9]:
cold_df = movie_sent.select_dtypes(exclude=["object"])
cold_df

movie_id  intelligent      real  touching  relatable       sad  \
0         8984     0.189474  0.147368  0.242105   0.168421  0.073684   
1         8985     0.137500  0.187500  0.275000   0.162500  0.025000   
2         8986     0.103093  0.051546  0.247423   0.092784  0.010309   
3         8987     0.063158  0.094737  0.294737   0.073684  0.031579   
4         8988     0.193548  0.225806  0.215054   0.172043  0.053763   
...        ...          ...       ...       ...        ...       ...   
2613     13526     0.042105  0.031579  0.042105   0.147368  0.031579   
2614     13527     0.329670  0.043956  0.098901   0.043956  0.120879   
2615     13528     0.018868  0.037736  0.037736   0.018868  0.018868   
2616     13529     0.125786  0.037736  0.113208   0.056604  0.106918   
2617     13532     0.222222  0.049383  0.037037   0.049383  0.049383   

      romantic  informative      mean      fake  ...  info_real_int_insp  \
0     0.431579     0.200000  0.094737  0.021053  ...            0.176316   
1     0.450000     0.100000  0.037500  0.050000  ...            0.165625   
2     0.556701     0.051546  0.000000  0.030928  ...            0.087629   
3     0.589474     0.042105  0.000000  0.052632  ...            0.089474   
4     0.247312     0.182796  0.064516  0.064516  ...            0.206989   
...        ...          ...       ...       ...  ...                 ...   
2613  0.084211     0.031579  0.010526  0.042105  ...            0.042105   
2614  0.010989     0.010989  0.021978  0.010989  ...            0.104396   
2615  0.000000     0.018868  0.037736  0.075472  ...            0.028302   
2616  0.006289     0.025157  0.000000  0.012579  ...            0.094340   
2617  0.012346     0.061728  0.000000  0.037037  ...            0.108025   

      fun_outrag_mindless  fastpaced_thrilling_exciting  \
0                0.143860                      0.161404   
1                0.133333                      0.083333   
2                0.147766                      0.089347   
3                0.108772                      0.045614   
4                0.182796                      0.200717   
...                   ...                           ...   
2613             0.421053                      0.150877   
2614             0.040293                      0.542125   
2615             0.094340                      0.264151   
2616             0.115304                      0.446541   
2617             0.111111                      0.452675   

      scary_dist_edgy_thrill  origi_imagin_fresh_imag  \
0                   0.084211                 0.142105   
1                   0.043750                 0.156250   
2                   0.020619                 0.095361   
3                   0.015789                 0.092105   
4                   0.112903                 0.174731   
...                      ...                      ...   
2613                0.068421                 0.150000   
2614                0.373626                 0.288462   
2615                0.424528                 0.066038   
2616                0.172956                 0.243711   
2617                0.225309                 0.222222   

      sad_dramatic_deep_touching  fake_unrel_unorig_predic  sexy_glam_rom  \
0                       0.147368                  0.071053       0.217544   
1                       0.131250                  0.081250       0.220833   
2                       0.095361                  0.074742       0.230241   
3                       0.113158                  0.097368       0.228070   
4                       0.142473                  0.083333       0.161290   
...                          ...                       ...            ...   
2613                    0.047368                  0.026316       0.084211   
2614                    0.222527                  0.010989       0.084249   
2615                    0.061321                  0.066038       0.025157   
2616                    0.205975                  0.017296      

### standardization

In [10]:
cold_df = cold_df.drop(columns=['movie_id'])

In [11]:
from sklearn.preprocessing import StandardScaler
import numpy as np

# the scaler object (model)
scaler = StandardScaler()
# fit and transform the data
scaled_data = scaler.fit_transform(cold_df) 

In [12]:
cold_df = pd.DataFrame(scaled_data)

In [13]:
cold_df

0         1         2         3         4         5         6   \
0     0.416378  0.480964  0.802676  1.270701 -0.140396  1.661868  1.394648   
1    -0.097149  0.916437  1.068537  1.179405 -0.621078  1.763837  0.254496   
2    -0.437110 -0.558813  0.845653  0.104444 -0.766126  2.354471 -0.297949   
3    -0.831688 -0.090148  1.228054 -0.190049 -0.556121  2.535882 -0.405592   
4     0.456638  1.332105  0.584041  1.326549 -0.337083  0.641873  1.198493   
...        ...       ...       ...       ...       ...       ...       ...   
2613 -1.039699 -0.775483 -0.813759  0.946090 -0.556121 -0.260961 -0.525608   
2614  1.801595 -0.641177 -0.354725 -0.648428  0.325581 -0.666273 -0.760365   
2615 -1.269296 -0.708673 -0.849074 -1.035263 -0.681623 -0.727101 -0.670533   
2616 -0.212888 -0.708673 -0.239098 -0.453413  0.187739 -0.692287 -0.598825   
2617  0.739951 -0.582292 -0.854722 -0.564754 -0.380336 -0.658763 -0.181858   

            7         8         9   ...        34        35        36  \
0     2.017199 -0.684231  1.158880  ...  0.870926 -0.286715 -0.615845   
1     0.259153  0.047294  1.542467  ...  0.728294 -0.380270 -1.158841   
2    -0.892670 -0.434676  0.515615  ... -0.312291 -0.251993 -1.117014   
3    -0.892670  0.113797 -0.273176  ... -0.287678 -0.598567 -1.421187   
4     1.088961  0.414130  1.829813  ...  1.280156  0.059341 -0.342411   
...        ...       ...       ...  ...       ...       ...       ...   
2613 -0.569351 -0.152213 -0.682335  ... -0.919644  2.176921 -0.689058   
2614 -0.217609 -0.938548 -0.246199  ... -0.088597 -1.207194  2.032159   
2615  0.266397  0.690987 -0.520216  ... -1.103802 -0.726839  0.098788   
2616 -0.892670 -0.898377 -0.397983  ... -0.222759 -0.540512  1.367353   
2617 -0.892670 -0.280291 -0.167098  ... -0.040180 -0.577777  1.410016   

            37        38        39        40        41        42        43  
0    -0.614630 -0.320762 -0.027937  0.711468  1.549888  0.832874  0.438026  
1    -0.967269 -0.093038 -0.216216  1.091029  1.587765  1.260930 -0.606673  
2    -1.168874 -1.073330 -0.635437  0.848802  1.696087  1.864140 -1.186243  
3    -1.210962 -1.125743 -0.427549  1.690981  1.671096  1.733013 -1.395252  
4    -0.364556  0.204502 -0.085119  1.168574  0.902142  0.396903  0.479770  
...        ...       ...       ...       ...       ...       ...       ...  
2613 -0.752245 -0.193660 -1.196034 -0.953703  0.014586 -0.654311  0.545866  
2614  1.907808  2.035518  0.849993 -1.524188  0.015030 -0.752798  2.887531  
2615  2.351450 -1.545420 -1.033058  0.524806 -0.665399 -0.991771  0.429887  
2616  0.158841  1.315046  0.656643 -1.289448 -0.786099 -0.337035 -0.858766  
2617  0.615127  0.969090 -0.451458  0.594169 -0.718149 -0.513710 -0.111825  

[2618 rows x 44 columns]

In [14]:
cold_df['KM11'] = movie_sent['KM11']
cold_df

0         1         2         3         4         5         6  \
0     0.416378  0.480964  0.802676  1.270701 -0.140396  1.661868  1.394648   
1    -0.097149  0.916437  1.068537  1.179405 -0.621078  1.763837  0.254496   
2    -0.437110 -0.558813  0.845653  0.104444 -0.766126  2.354471 -0.297949   
3    -0.831688 -0.090148  1.228054 -0.190049 -0.556121  2.535882 -0.405592   
4     0.456638  1.332105  0.584041  1.326549 -0.337083  0.641873  1.198493   
...        ...       ...       ...       ...       ...       ...       ...   
2613 -1.039699 -0.775483 -0.813759  0.946090 -0.556121 -0.260961 -0.525608   
2614  1.801595 -0.641177 -0.354725 -0.648428  0.325581 -0.666273 -0.760365   
2615 -1.269296 -0.708673 -0.849074 -1.035263 -0.681623 -0.727101 -0.670533   
2616 -0.212888 -0.708673 -0.239098 -0.453413  0.187739 -0.692287 -0.598825   
2617  0.739951 -0.582292 -0.854722 -0.564754 -0.380336 -0.658763 -0.181858   

             7         8         9  ...        35        36        37  \
0     2.017199 -0.684231  1.158880  ... -0.286715 -0.615845 -0.614630   
1     0.259153  0.047294  1.542467  ... -0.380270 -1.158841 -0.967269   
2    -0.892670 -0.434676  0.515615  ... -0.251993 -1.117014 -1.168874   
3    -0.892670  0.113797 -0.273176  ... -0.598567 -1.421187 -1.210962   
4     1.088961  0.414130  1.829813  ...  0.059341 -0.342411 -0.364556   
...        ...       ...       ...  ...       ...       ...       ...   
2613 -0.569351 -0.152213 -0.682335  ...  2.176921 -0.689058 -0.752245   
2614 -0.217609 -0.938548 -0.246199  ... -1.207194  2.032159  1.907808   
2615  0.266397  0.690987 -0.520216  ... -0.726839  0.098788  2.351450   
2616 -0.892670 -0.898377 -0.397983  ... -0.540512  1.367353  0.158841   
2617 -0.892670 -0.280291 -0.167098  ... -0.577777  1.410016  0.615127   

            38        39        40        41        42        43  KM11  
0    -0.320762 -0.027937  0.711468  1.549888  0.832874  0.438026     2  
1    -0.093038 -0.216216  1.091029  1.587765  1.260930 -0.606673     1  
2    -1.073330 -0.635437  0.848802  1.696087  1.864140 -1.186243     1  
3    -1.125743 -0.427549  1.690981  1.671096  1.733013 -1.395252     1  
4     0.204502 -0.085119  1.168574  0.902142  0.396903  0.479770     2  
...        ...       ...       ...       ...       ...       ...   ...  
2613 -0.193660 -1.196034 -0.953703  0.014586 -0.654311  0.545866     8  
2614  2.035518  0.849993 -1.524188  0.015030 -0.752798  2.887531     6  
2615 -1.545420 -1.033058  0.524806 -0.665399 -0.991771  0.429887     5  
2616  1.315046  0.656643 -1.289448 -0.786099 -0.337035 -0.858766     4  
2617  0.969090 -0.451458  0.594169 -0.718149 -0.513710 -0.111825     7  

[2618 rows x 45 columns]

### Let's put the cluster 2 in the test dataset

In [15]:
df_test = cold_df[cold_df['KM11'] == 2] 
x_test = df_test.iloc[:, 0:44]
y_test = df_test.iloc[:, 44:]

### cold_df has all the other clusters

In [16]:
cold_df = cold_df[cold_df['KM11'] != 2] 
cold_df

0         1         2         3         4         5         6  \
1    -0.097149  0.916437  1.068537  1.179405 -0.621078  1.763837  0.254496   
2    -0.437110 -0.558813  0.845653  0.104444 -0.766126  2.354471 -0.297949   
3    -0.831688 -0.090148  1.228054 -0.190049 -0.556121  2.535882 -0.405592   
5    -0.935694 -0.661260  1.142978  0.134562 -0.660052  2.710684 -0.645624   
6     0.152736  0.269785  1.383366  1.363178 -0.408684  1.590050  0.970405   
...        ...       ...       ...       ...       ...       ...       ...   
2613 -1.039699 -0.775483 -0.813759  0.946090 -0.556121 -0.260961 -0.525608   
2614  1.801595 -0.641177 -0.354725 -0.648428  0.325581 -0.666273 -0.760365   
2615 -1.269296 -0.708673 -0.849074 -1.035263 -0.681623 -0.727101 -0.670533   
2616 -0.212888 -0.708673 -0.239098 -0.453413  0.187739 -0.692287 -0.598825   
2617  0.739951 -0.582292 -0.854722 -0.564754 -0.380336 -0.658763 -0.181858   

             7         8         9  ...        35        36        37  \
1     0.259153  0.047294  1.542467  ... -0.380270 -1.158841 -0.967269   
2    -0.892670 -0.434676  0.515615  ... -0.251993 -1.117014 -1.168874   
3    -0.892670  0.113797 -0.273176  ... -0.598567 -1.421187 -1.210962   
5    -0.892670  0.113797 -0.273176  ... -0.224344 -1.347974 -1.279770   
6    -0.178361 -0.334707  0.695008  ...  0.019336 -0.848821 -0.689839   
...        ...       ...       ...  ...       ...       ...       ...   
2613 -0.569351 -0.152213 -0.682335  ...  2.176921 -0.689058 -0.752245   
2614 -0.217609 -0.938548 -0.246199  ... -1.207194  2.032159  1.907808   
2615  0.266397  0.690987 -0.520216  ... -0.726839  0.098788  2.351450   
2616 -0.892670 -0.898377 -0.397983  ... -0.540512  1.367353  0.158841   
2617 -0.892670 -0.280291 -0.167098  ... -0.577777  1.410016  0.615127   

            38        39        40        41        42        43  KM11  
1    -0.093038 -0.216216  1.091029  1.587765  1.260930 -0.606673     1  
2    -1.073330 -0.635437  0.848802  1.696087  1.864140 -1.186243     1  
3    -1.125743 -0.427549  1.690981  1.671096  1.733013 -1.395252     1  
5    -1.125743 -0.489028  0.907371  1.751901  1.302512 -1.503092     1  
6    -0.221741  0.118254  0.663632  1.365727  1.305242 -0.192712     1  
...        ...       ...       ...       ...       ...       ...   ...  
2613 -0.193660 -1.196034 -0.953703  0.014586 -0.654311  0.545866     8  
2614  2.035518  0.849993 -1.524188  0.015030 -0.752798  2.887531     6  
2615 -1.545420 -1.033058  0.524806 -0.665399 -0.991771  0.429887     5  
2616  1.315046  0.656643 -1.289448 -0.786099 -0.337035 -0.858766     4  
2617  0.969090 -0.451458  0.594169 -0.718149 -0.513710 -0.111825     7  

[2350 rows x 45 columns]

In [17]:
X = cold_df.iloc[:, 0:44]
y = cold_df.iloc[:, 44:]

##### Let's use a third of the dataset as validation set

In [18]:
import numpy as np
from sklearn.model_selection import train_test_split

In [19]:
 x_train, x_val, y_train, y_val = train_test_split(X, y, test_size=0.35, random_state=5)
y_train=y_train.astype('int')
y_val=y_val.astype('int')
y_test=y_test.astype('int')

In [20]:
y_val.value_counts()

KM11
8       136
7       126
1       106
6       101
3        98
5        80
9        71
0        53
4        52
dtype: int64

In [21]:
y_train.value_counts()

KM11
8       252
1       231
7       229
3       183
6       173
5       151
9       114
4       106
0        88
dtype: int64

##### NOw we are ready to implement a random forest model

In [22]:
from sklearn import model_selection
from sklearn.ensemble import RandomForestClassifier
rfc = RandomForestClassifier()
# random forest model creation
rfc = RandomForestClassifier()
rfc.fit(x_train,y_train.values.ravel())
# predictions
rfc_predict = rfc.predict(x_val)


In [23]:
from sklearn.model_selection import cross_val_score
from sklearn.metrics import classification_report, confusion_matrix

In [24]:
rfc_cv_score = cross_val_score(rfc, x_train, y_train.values.ravel(), cv=10, scoring='accuracy')


#### Results on validation set

In [25]:
print("=== Confusion Matrix ===")
print(confusion_matrix(y_val, rfc_predict))
print('\n')
print("=== Classification Report ===")
print(classification_report(y_val, rfc_predict))
print('\n')
print("=== All AUC Scores ===")
print(rfc_cv_score)
print('\n')
print("=== Mean AUC Score ===")
print("Mean AUC Score - Random Forest: ", rfc_cv_score.mean())

=== Confusion Matrix ===
[[ 44   4   3   1   0   0   0   0   1]
 [  0  99   3   1   0   2   0   1   0]
 [  2   3  86   1   0   0   2   3   1]
 [  0   0   2  35   0   8   6   1   0]
 [  0   0   0   0  70   4   6   0   0]
 [  0   0   0   0   4  87   9   0   1]
 [  0   0   0   2   3   0 120   1   0]
 [  0   1   5   0   0   0   1 129   0]
 [  0   1   0   0   0   9   0   0  61]]


=== Classification Report ===
              precision    recall  f1-score   support

           0       0.96      0.83      0.89        53
           1       0.92      0.93      0.93       106
           3       0.87      0.88      0.87        98
           4       0.88      0.67      0.76        52
           5       0.91      0.88      0.89        80
           6       0.79      0.86      0.82       101
           7       0.83      0.95      0.89       126
           8       0.96      0.95      0.95       136
           9       0.95      0.86      0.90        71

    accuracy                           0.89      

In [26]:
rfc_predict = rfc.predict(x_test)

In [27]:
rfc_predict

array([1, 1, 1, 9, 1, 6, 8, 1, 9, 1, 6, 6, 9, 6, 9, 9, 1, 9, 9, 6, 6, 1,
       6, 4, 9, 1, 6, 9, 1, 5, 8, 9, 9, 5, 9, 1, 1, 5, 3, 6, 3, 6, 9, 5,
       9, 6, 9, 9, 9, 6, 6, 5, 6, 6, 5, 6, 6, 5, 9, 9, 6, 6, 9, 3, 9, 7,
       9, 3, 8, 9, 1, 9, 1, 7, 3, 6, 5, 1, 8, 9, 7, 8, 8, 9, 3, 9, 1, 1,
       9, 9, 7, 6, 3, 6, 7, 9, 7, 1, 1, 6, 6, 7, 1, 1, 7, 9, 8, 3, 9, 6,
       4, 7, 3, 1, 3, 3, 5, 6, 1, 6, 9, 1, 6, 5, 8, 3, 7, 3, 9, 3, 6, 9,
       6, 9, 9, 7, 1, 1, 9, 6, 1, 1, 6, 6, 8, 9, 3, 1, 9, 6, 9, 1, 6, 3,
       6, 1, 3, 9, 1, 9, 9, 9, 9, 9, 6, 6, 1, 9, 9, 1, 3, 6, 6, 7, 0, 8,
       9, 3, 1, 9, 1, 1, 5, 7, 1, 1, 1, 1, 5, 8, 3, 9, 7, 9, 8, 8, 3, 4,
       8, 6, 3, 6, 9, 3, 6, 9, 9, 6, 6, 9, 6, 4, 9, 9, 8, 7, 6, 7, 6, 4,
       1, 6, 1, 7, 6, 8, 3, 6, 4, 8, 6, 8, 8, 9, 1, 6, 6, 6, 7, 6, 6, 1,
       6, 5, 8, 9, 6, 9, 5, 5, 9, 5, 1, 6, 8, 4, 5, 1, 9, 8, 5, 8, 7, 8,
       8, 9, 8, 5])

In [29]:
movie_2 = movie_sent[movie_sent['KM11'] != 2] 
movie_2

movie_id  intelligent      real  touching  relatable       sad  \
1         8985     0.137500  0.187500  0.275000   0.162500  0.025000   
2         8986     0.103093  0.051546  0.247423   0.092784  0.010309   
3         8987     0.063158  0.094737  0.294737   0.073684  0.031579   
5         8989     0.052632  0.042105  0.284211   0.094737  0.021053   
6         8990     0.162791  0.127907  0.313953   0.174419  0.046512   
...        ...          ...       ...       ...        ...       ...   
2613     13526     0.042105  0.031579  0.042105   0.147368  0.031579   
2614     13527     0.329670  0.043956  0.098901   0.043956  0.120879   
2615     13528     0.018868  0.037736  0.037736   0.018868  0.018868   
2616     13529     0.125786  0.037736  0.113208   0.056604  0.106918   
2617     13532     0.222222  0.049383  0.037037   0.049383  0.049383   

      romantic  informative      mean      fake  ...  fun_outrag_mindless  \
1     0.450000     0.100000  0.037500  0.050000  ...             0.133333   
2     0.556701     0.051546  0.000000  0.030928  ...             0.147766   
3     0.589474     0.042105  0.000000  0.052632  ...             0.108772   
5     0.621053     0.021053  0.000000  0.052632  ...             0.150877   
6     0.418605     0.162791  0.023256  0.034884  ...             0.178295   
...        ...          ...       ...       ...  ...                  ...   
2613  0.084211     0.031579  0.010526  0.042105  ...             0.421053   
2614  0.010989     0.010989  0.021978  0.010989  ...             0.040293   
2615  0.000000     0.018868  0.037736  0.075472  ...             0.094340   
2616  0.006289     0.025157  0.000000  0.012579  ...             0.115304   
2617  0.012346     0.061728  0.000000  0.037037  ...             0.111111   

      fastpaced_thrilling_exciting  scary_dist_edgy_thrill  \
1                         0.083333                0.043750   
2                         0.089347                0.020619   
3                         0.045614                0.015789   
5                         0.056140                0.007895   
6                         0.127907                0.075581   
...                            ...                     ...   
2613                      0.150877                0.068421   
2614                      0.542125                0.373626   
2615                      0.264151                0.424528   
2616                      0.446541                0.172956   
2617                      0.452675                0.225309   

      origi_imagin_fresh_imag  sad_dramatic_deep_touching  \
1                    0.156250                    0.131250   
2                    0.095361                    0.095361   
3                    0.092105                    0.113158   
5                    0.092105                    0.107895   
6                    0.148256                    0.159884   
...                       ...                         ...   
2613                 0.150000                    0.047368   
2614                 0.288462                    0.222527   
2615                 0.066038                    0.061321   
2616                 0.243711                    0.205975   
2617                 0.222222                    0.111111   

      fake_unrel_unorig_predic  sexy_glam_rom  touching_wholesome_uplifting  \
1                     0.081250       0.220833                      0.220833   
2                     0.074742       0.230241                      0.274914   
3                     0.097368       0.228070                      0.263158   
5                     0.076316       0.235088                      0.224561   
6                     0.069767       0.201550                      0.224806   
...                        ...            ...                           ...   
2613                  0.026316       0.084211                      0.049123   
2614                  0.010989       0.084249                      0.040293   
2615                  0.066

In [30]:
movie_1 = movie_sent[movie_sent['KM11'] == 2] 
movie_1 = movie_1.drop(columns=['KM11'])
movie_1 = movie_1.assign(KM11=rfc_predict)
movie_1

movie_id  intelligent      real  touching  relatable       sad  \
0         8984     0.189474  0.147368  0.242105   0.168421  0.073684   
4         8988     0.193548  0.225806  0.215054   0.172043  0.053763   
7         8991     0.260417  0.177083  0.229167   0.104167  0.031250   
8         8992     0.239130  0.173913  0.173913   0.184783  0.097826   
11        8995     0.228261  0.130435  0.239130   0.119565  0.076087   
...        ...          ...       ...       ...        ...       ...   
2564     13394     0.156863  0.176471  0.058824   0.098039  0.039216   
2565     13403     0.131148  0.114754  0.098361   0.098361  0.114754   
2567     13407     0.173077  0.096154  0.134615   0.173077  0.057692   
2570     13413     0.074074  0.129630  0.129630   0.074074  0.055556   
2594     13486     0.122807  0.052632  0.035088   0.070175  0.070175   

      romantic  informative      mean      fake  ...  fun_outrag_mindless  \
0     0.431579     0.200000  0.094737  0.021053  ...             0.143860   
4     0.247312     0.182796  0.064516  0.064516  ...             0.182796   
7     0.500000     0.187500  0.125000  0.052083  ...             0.152778   
8     0.184783     0.239130  0.184783  0.086957  ...             0.152174   
11    0.271739     0.217391  0.097826  0.010870  ...             0.159420   
...        ...          ...       ...       ...  ...                  ...   
2564  0.117647     0.137255  0.078431  0.098039  ...             0.098039   
2565  0.081967     0.196721  0.098361  0.049180  ...             0.092896   
2567  0.192308     0.250000  0.134615  0.057692  ...             0.147436   
2570  0.074074     0.148148  0.055556  0.055556  ...             0.123457   
2594  0.105263     0.087719  0.140351  0.017544  ...             0.128655   

      fastpaced_thrilling_exciting  scary_dist_edgy_thrill  \
0                         0.161404                0.084211   
4                         0.200717                0.112903   
7                         0.201389                0.096354   
8                         0.246377                0.184783   
11                        0.224638                0.119565   
...                            ...                     ...   
2564                      0.196078                0.147059   
2565                      0.136612                0.094262   
2567                      0.217949                0.144231   
2570                      0.160494                0.111111   
2594                      0.292398                0.285088   

      origi_imagin_fresh_imag  sad_dramatic_deep_touching  \
0                    0.142105                    0.147368   
4                    0.174731                    0.142473   
7                    0.187500                    0.158854   
8                    0.195652                    0.138587   
11                   0.201087                    0.165761   
...                       ...                         ...   
2564                 0.132353                    0.058824   
2565                 0.135246                    0.110656   
2567                 0.158654                    0.158654   
2570                 0.138889                    0.125000   
2594                 0.162281                    0.135965   

      fake_unrel_unorig_predic  sexy_glam_rom  touching_wholesome_uplifting  \
0                     0.071053       0.217544                      0.182456   
4                     0.083333       0.161290                      0.143369   
7                     0.070312       0.305556                      0.156250   
8                     0.089674       0.170290                      0.123188   
11                    0.059783       0.224638                      0.152174   
...                        ...            ...                           ...   
2564                  0.078431       0.071895                      0.045752   
2565                  0.045082       0.092896                      0.060109   
2567                  0.110

In [31]:
movie_sent_cluster = pd.concat([movie_1, movie_2])
movie_sent_cluster

movie_id  intelligent      real  touching  relatable       sad  \
0         8984     0.189474  0.147368  0.242105   0.168421  0.073684   
4         8988     0.193548  0.225806  0.215054   0.172043  0.053763   
7         8991     0.260417  0.177083  0.229167   0.104167  0.031250   
8         8992     0.239130  0.173913  0.173913   0.184783  0.097826   
11        8995     0.228261  0.130435  0.239130   0.119565  0.076087   
...        ...          ...       ...       ...        ...       ...   
2613     13526     0.042105  0.031579  0.042105   0.147368  0.031579   
2614     13527     0.329670  0.043956  0.098901   0.043956  0.120879   
2615     13528     0.018868  0.037736  0.037736   0.018868  0.018868   
2616     13529     0.125786  0.037736  0.113208   0.056604  0.106918   
2617     13532     0.222222  0.049383  0.037037   0.049383  0.049383   

      romantic  informative      mean      fake  ...  fun_outrag_mindless  \
0     0.431579     0.200000  0.094737  0.021053  ...             0.143860   
4     0.247312     0.182796  0.064516  0.064516  ...             0.182796   
7     0.500000     0.187500  0.125000  0.052083  ...             0.152778   
8     0.184783     0.239130  0.184783  0.086957  ...             0.152174   
11    0.271739     0.217391  0.097826  0.010870  ...             0.159420   
...        ...          ...       ...       ...  ...                  ...   
2613  0.084211     0.031579  0.010526  0.042105  ...             0.421053   
2614  0.010989     0.010989  0.021978  0.010989  ...             0.040293   
2615  0.000000     0.018868  0.037736  0.075472  ...             0.094340   
2616  0.006289     0.025157  0.000000  0.012579  ...             0.115304   
2617  0.012346     0.061728  0.000000  0.037037  ...             0.111111   

      fastpaced_thrilling_exciting  scary_dist_edgy_thrill  \
0                         0.161404                0.084211   
4                         0.200717                0.112903   
7                         0.201389                0.096354   
8                         0.246377                0.184783   
11                        0.224638                0.119565   
...                            ...                     ...   
2613                      0.150877                0.068421   
2614                      0.542125                0.373626   
2615                      0.264151                0.424528   
2616                      0.446541                0.172956   
2617                      0.452675                0.225309   

      origi_imagin_fresh_imag  sad_dramatic_deep_touching  \
0                    0.142105                    0.147368   
4                    0.174731                    0.142473   
7                    0.187500                    0.158854   
8                    0.195652                    0.138587   
11                   0.201087                    0.165761   
...                       ...                         ...   
2613                 0.150000                    0.047368   
2614                 0.288462                    0.222527   
2615                 0.066038                    0.061321   
2616                 0.243711                    0.205975   
2617                 0.222222                    0.111111   

      fake_unrel_unorig_predic  sexy_glam_rom  touching_wholesome_uplifting  \
0                     0.071053       0.217544                      0.182456   
4                     0.083333       0.161290                      0.143369   
7                     0.070312       0.305556                      0.156250   
8                     0.089674       0.170290                      0.123188   
11                    0.059783       0.224638                      0.152174   
...                        ...            ...                           ...   
2613                  0.026316       0.084211                      0.049123   
2614                  0.010989       0.084249                      0.040293   
2615                  0.066

In [36]:
names = movie[['movie_id', 'movie_name']]

In [37]:
movie_sent_3 = movie_sent_cluster.merge(names, on='movie_id', how='left')
movie_sent_3

movie_id  intelligent      real  touching  relatable       sad  \
0         8984     0.189474  0.147368  0.242105   0.168421  0.073684   
1         8988     0.193548  0.225806  0.215054   0.172043  0.053763   
2         8991     0.260417  0.177083  0.229167   0.104167  0.031250   
3         8992     0.239130  0.173913  0.173913   0.184783  0.097826   
4         8995     0.228261  0.130435  0.239130   0.119565  0.076087   
...        ...          ...       ...       ...        ...       ...   
2613     13526     0.042105  0.031579  0.042105   0.147368  0.031579   
2614     13527     0.329670  0.043956  0.098901   0.043956  0.120879   
2615     13528     0.018868  0.037736  0.037736   0.018868  0.018868   
2616     13529     0.125786  0.037736  0.113208   0.056604  0.106918   
2617     13532     0.222222  0.049383  0.037037   0.049383  0.049383   

      romantic  informative      mean      fake  ...  \
0     0.431579     0.200000  0.094737  0.021053  ...   
1     0.247312     0.182796  0.064516  0.064516  ...   
2     0.500000     0.187500  0.125000  0.052083  ...   
3     0.184783     0.239130  0.184783  0.086957  ...   
4     0.271739     0.217391  0.097826  0.010870  ...   
...        ...          ...       ...       ...  ...   
2613  0.084211     0.031579  0.010526  0.042105  ...   
2614  0.010989     0.010989  0.021978  0.010989  ...   
2615  0.000000     0.018868  0.037736  0.075472  ...   
2616  0.006289     0.025157  0.000000  0.012579  ...   
2617  0.012346     0.061728  0.000000  0.037037  ...   

      fastpaced_thrilling_exciting  scary_dist_edgy_thrill  \
0                         0.161404                0.084211   
1                         0.200717                0.112903   
2                         0.201389                0.096354   
3                         0.246377                0.184783   
4                         0.224638                0.119565   
...                            ...                     ...   
2613                      0.150877                0.068421   
2614                      0.542125                0.373626   
2615                      0.264151                0.424528   
2616                      0.446541                0.172956   
2617                      0.452675                0.225309   

      origi_imagin_fresh_imag  sad_dramatic_deep_touching  \
0                    0.142105                    0.147368   
1                    0.174731                    0.142473   
2                    0.187500                    0.158854   
3                    0.195652                    0.138587   
4                    0.201087                    0.165761   
...                       ...                         ...   
2613                 0.150000                    0.047368   
2614                 0.288462                    0.222527   
2615                 0.066038                    0.061321   
2616                 0.243711                    0.205975   
2617                 0.222222                    0.111111   

      fake_unrel_unorig_predic  sexy_glam_rom  touching_wholesome_uplifting  \
0                     0.071053       0.217544                      0.182456   
1                     0.083333       0.161290                      0.143369   
2                     0.070312       0.305556                      0.156250   
3                     0.089674       0.170290                      0.123188   
4                     0.059783       0.224638                      0.152174   
...                        ...            ...                           ...   
2613                  0.026316       0.084211                      0.049123   
2614                  0.010989       0.084249                      0.040293   
2615                  0.066038       0.025157                      0.018868   
2616                  0.017296       0.014675                      0.077568   
2617                  0.067901       0.020576                      0.061728   

      mean_edgy  KM11                    

In [38]:
movie_sent_3.to_csv('../movie_sent_km11.csv', index=False)
